@baseUrl = http://localhost:4000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdlZDFjNjc2NDFhOGQ2OWZjOWM0MTYiLCJuYW1lIjoiQW5pcnVkaDMzMyIsImVtYWlsIjoiYW5pcnVkaDMzM0BnbWFpbC5jb20iLCJpYXQiOjE2ODYwMzI4NjAsImV4cCI6MTY4NjAzNjQ2MH0.HF2PzSOx1r3_9zSYIRjyuuFrX8ZGqDvABY1VopEoi1Q

###
POST {{baseUrl}}/task
Content-Type: application/json

{
   "title":"task1",
    "description":"fagrreryh",
    "priority":"medium",
    "assignee":"647ed1c67641a8d69fc9c416"

}

###
GET  {{baseUrl}}/task

###
GET {{baseUrl}}/task/647ecf807641a8d69fc9c412

###
DELETE {{baseUrl}}/task/647ecf807641a8d69fc9c412
Authorization: bearer {{token}}



###
POST {{baseUrl}}/task/assign/647eceb97641a8d69fc9c40f
Content-Type: application/json
Authorization: bearer {{token}}

{
    "assigneeEmail":"anirudh333@gmail.com"
}


###
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "name":"Anirudh333",
    "email":"anirudh333@gmail.com",
    "password":"Password@573",
    "mobile":"+447893932118"
}

###
POST {{baseUrl}}/auth/mobile-otp-verification
Content-Type: application/json

{
    "mobile": "+447893932118",
    "otp" : "6231"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"anirudh333@gmail.com",
    "password":"Password@573"
}

###
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: bearer {{token}}

{
    "email":"anirudh12122@gmail.com",
    "password":"Password@573"
}