@baseUrl = http://localhost:4000/api


@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdmMmU5OTcxNjhiMjE3YjRkNGQyNzciLCJuYW1lIjoiQW5pcnVkaDEiLCJlbWFpbCI6ImFuaXJ1ZGgxQGdtYWlsLmNvbSIsImlhdCI6MTY4NjA1NjYxMywiZXhwIjoxNjg2MDYwMjEzfQ.oEEekAknGT6uQOsK82gWm2216b5FzrxiVJFWDL8NXvw



// create task
###
POST {{baseUrl}}/task
Content-Type: application/json

{
   "title":"task2",
    "description":"run",
    "priority":"high",
    "createdBy":"647f2e997168b217b4d4d277"

}



//get task
###
GET  {{baseUrl}}/task


//get task by id
###
GET {{baseUrl}}/task/647f2ee67168b217b4d4d27d


//delete task
###
DELETE {{baseUrl}}/task/647f0e913bdd273accc55429
Authorization: bearer {{token}}



//assign task
###
POST {{baseUrl}}/task/assign/647f2226ddf6904ec7fd3522
Content-Type: application/json
Authorization: bearer {{token}}

{
    "assigneeEmail":"anirudh1209@gmail.com"
}



//change status
###
POST {{baseUrl}}/task/status/647f2226ddf6904ec7fd3522
Content-Type: application/json
Authorization: bearer {{token}}

{
    "status":"done"
}

###
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "name":"Anirudh1",
    "email":"anirudh1@gmail.com",
    "password":"Password@573",
    "mobile":"+447893932118"
}

###
POST {{baseUrl}}/auth/mobile-otp-verification
Content-Type: application/json

{
    "mobile": "+447893932118",
    "otp" : "5491"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"anirudh1@gmail.com",
    "password":"Password@573"
}

###
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: bearer {{token}}

{
    "email":"anirudh12122@gmail.com",
    "password":"Password@573"
}